services:
  web:
    build:
      context: .
    container_name: django_web
    command: gunicorn yanafamily.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    env_file:
      - .env
    networks:
      - my_shared_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
    depends_on:
      - web
    networks:
      - my_shared_network

volumes:
  static_volume:

networks:
  my_shared_network:
    external: true
