version: '3.8'

services:
  web:
    build:
      context: .
    container_name: django_web
    command: gunicorn yanafamily.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./staticfiles:/app/staticfiles
    depends_on:
      - web

volumes:
  static_volume:
