version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8000"  # Maps port 8080 on the host to 8000 in the container
    environment:
      - DEBUG=0
      - ALLOWED_HOSTS=31.128.39.108
    restart: always
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
    depends_on:
      - web

volumes:
  static_volume:
